apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: config-demo
build:
  artifacts:
  - image: frayer/spring-boot-config-demo
deploy:
  kubectl:
    manifests:
    - k8s/configmap.yaml
    - k8s/deployment.yaml
portForward:
  - resourceType: deployment
    resourceName: spring-boot-config-demo
    namespace: default
    port: 8080
    localPort: 8080
